# Generated by Django 5.2.6 on 2025-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy'), ('BIO', 'Biography'), ('HIS', 'History'), ('EDU', 'Educational')], default='FIC', max_length=50),
        ),
    ]
